baseURL: "https://jaafarmehrez.github.io/jaafarmehrez.github.io/" 
title: Jaafar Mehrez
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://medium.com/@jfrmhrzz         
          weight: 6

params:
    description: "This is just a place for my random thoughts.."
    author: Jaafar Mehrez
    googleAnalyticsID: "G-NH7SJB0T7E"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jaafar Mehrez
          subtitle: "This is just a place for my random thoughts..The site is still under construction.."
          imageUrl: "DOOM.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://medium.com/@jfrmhrzz

    socialIcons:
        - name: CV
          url: 
        - name: Email
          url: mailto:jfrmhrzz@gmail.com
        - name: Zoom
          url: https://www.zoom.us/my/jaafarmehrez
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=pfztAw8AAAAJ
        - name: Researchgate
          url: https://www.researchgate.net/profile/Jaafar-Mehrez
        - name: GitHub
          url: https://github.com/JaafarMehrez
        - name: Stackexchange
          url: https://mattermodeling.stackexchange.com/users/1554/jaafar-mehrez
        - name: Buymeacoffee
          url: https://buymeacoffee.com/jaafarmehrez
        - name: Kofi
          url: https://ko-fi.com/jaafarmehrez
        - name: Linkedin
          url: https://www.linkedin.com/in/jaafar-mehrez
        - name: X
          url: https://x.com/jfrmhrzz

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jaafar Mehrez"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
